// crates/tools/port/react/fixtures/counter.tsx
import { useState, useEffect } from "react";
import { View, Text, Button } from "./primitives";

interface CounterProps {
    initial?: number;
}

export function Counter({ initial = 0 }: CounterProps) {
    const [count, setCount] = useState(initial);

    useEffect(() => {
        console.log("count:", count);
    }, [count]);

    return (
        <View>
            <Text>Count: {count}</Text>
            <Button label="Inc" onClick={() => setCount(count + 1)} />
        </View>
    );
}

// crates/tools/port/solid/fixtures/counter.tsx
import { createSignal, createEffect } from "solid-js";
import { View, Text, Button } from "./primitives";

interface CounterProps {
    initial?: number;
}

export function Counter(props: CounterProps) {
    const [count, setCount] = createSignal(props.initial ?? 0);

    createEffect(() => {
        console.log("count:", count());
    });

    return (
        <View>
            <Text>Count: {count()}</Text>
            <Button label="Inc" onClick={() => setCount(count() + 1)} />
        </View>
    );
}
