// crates/tools/port/solid/fixtures/timer.tsx
import { createSignal, createEffect, onCleanup } from "solid-js";

interface TimerProps {
    intervalMs: number;
}

export function Timer(props: TimerProps) {
    const [tick, setTick] = createSignal(0);

    createEffect(() => {
        const id = setInterval(() => setTick(tick() + 1), props.intervalMs);
        onCleanup(() => clearInterval(id));
    });

    return (
        <View>
            <Text>Tick: {tick()}</Text>
        </View>
    );
}

// crates/port/react/fixtures/timer.tsx
import { useState, useEffect } from "react";

interface TimerProps {
    intervalMs: number;
}

export function Timer({ intervalMs }: TimerProps) {
    const [tick, setTick] = useState(0);

    useEffect(() => {
        const id = setInterval(() => setTick(tick + 1), intervalMs);
        return () => clearInterval(id);
    }, [intervalMs]);

    return (
        <View>
            <Text>Tick: {tick}</Text>
        </View>
    );
}
