// crates/port/vue/fixtures/counter.vue
<script setup lang="ts">
import { ref, watchEffect, withDefaults } from 'vue';

interface CounterProps {
    initial?: number;
}

const props = withDefaults(defineProps<CounterProps>(), { initial: 0 });

const count = ref(props.initial);

watchEffect(() => {
    console.log('count:', count.value);
});

function increment() {
    count.value++;
}
</script>

<template>
    <View>
        <Text>Count: {{ count }}</Text>
        <Button label="Inc" @click="increment" />
    </View>
</template>

<style scoped>
.counter { padding: 12px; }
</style>

// crates/tools/port/project/fixtures/demo-app/src/Counter.tsx
import { useState, useEffect } from "react";

interface CounterProps {
    initial?: number;
}

export function Counter({ initial = 0 }: CounterProps) {
    const [count, setCount] = useState(initial);

    useEffect(() => {
        console.log("count:", count);
    }, [count]);

    return (
        <View>
            <Text>Count: {count}</Text>
            <Button label="Inc" onClick={() => setCount(count + 1)} />
        </View>
    );
}
