// crates/tools/cli/examples/external-export-suite/consumers/svelte/src/App.svelte
<script>
  // Generated Svelte wrappers, resolved from the components package.
  import Greeter from "external-export-suite-components/svelte/Greeter.svelte";
  import Stepper from "external-export-suite-components/svelte/Stepper.svelte";

  let greets = 0;
  let value = 0; // host owns the stepper's value
</script>

<main>
  <h1>Svelte consumer</h1>

  <section>
    <h2>&lt;Greeter&gt;</h2>
    <Greeter name="World" onGreet={() => (greets += 1)} />
    <p>greet events: <strong>{greets}</strong></p>
  </section>

  <section>
    <h2>&lt;Stepper&gt; (controlled)</h2>
    <Stepper label="Count" {value} onStep={(next) => (value = next)} />
    <p>value: <strong>{value}</strong></p>
  </section>
</main>

<style>
  main { font-family: system-ui, sans-serif; margin: 2rem; max-width: 40rem; }
</style>

// crates/tools/cli/examples/external-export-suite/consumers/angular/src/app.component.ts
import { Component } from "@angular/core";
// Generated standalone Angular wrappers (value props → @Input,
// callbacks → @Output EventEmitters).
import { GreeterComponent } from "external-export-suite-components/angular/greeter.component";
import { StepperComponent } from "external-export-suite-components/angular/stepper.component";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [GreeterComponent, StepperComponent],
  template: `
    <main>
      <h1>Angular consumer</h1>

      <section>
        <h2>&lt;Greeter&gt;</h2>
        <idl-greeter-ng [name]="'World'" (greet)="greets = greets + 1"></idl-greeter-ng>
        <p>greet events: <strong>{{ greets }}</strong></p>
      </section>

      <section>
        <h2>&lt;Stepper&gt; (controlled)</h2>
        <idl-stepper-ng [label]="'Count'" [value]="value" (step)="value = $event"></idl-stepper-ng>
        <p>value: <strong>{{ value }}</strong></p>
      </section>
    </main>
  `,
})
export class AppComponent {
  greets = 0;
  value = 0; // host owns the stepper's value
}
